name: Check-Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: latest

      - name: Setup Oculus
        shell: pwsh
        run: |
          $(New-Object System.Net.WebClient).DownloadFile("https://securecdn.oculus.com/binaries/download/?id=4377593722298679&access_token=OC%7C1592049031074901%7C", "OVRSDK.zip")
          Expand-Archive -Path ./OVRSDK.zip -DestinationPath ./external/OVRSDK

      - name: Prepare WinRT projection files
        run: |
          nuget restore
          msbuild DeviceHandler /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win10-x64 /t:Rebuild
        
      - name: Restore and build (publish)
        run: msbuild plugin_TouchLink /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win10-x64 /t:Publish /p:PublishProfile=plugin_TouchLink\Properties\PublishProfiles\FolderProfile.pubxml
        
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin_TouchLink
          path: plugin_TouchLink/bin/Release/net7.0/win10-x64/publish/
          if-no-files-found: error